/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#00616d',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-container': '#5a6178',
        'on-surface-variant': '#b9cbb9',
        'surface-dim': '#131313',
        'outline-variant': '#3b4b3d',
        'surface-variant': '#353534',
        'surface-bright': '#3a3939',
        'tertiary': '#fcfaff',
        'inverse-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'background': '#131313',
        'error-container': '#93000a',
        'on-primary-container': '#007139',
        'secondary-fixed': '#9cf0ff',
        'outline': '#849585',
        'secondary': '#bdf4ff',
        'on-tertiary': '#283044',
        'tertiary-container': '#d6def8',
        'surface-container-high': '#2a2a2a',
        'secondary-container': '#00e3fd',
        'inverse-primary': '#006d37',
        'on-surface': '#e5e2e1',
        'on-error': '#690005',
        'primary': '#f1ffef',
        'on-primary': '#003919',
        'primary-container': '#00ff88',
        'surface-tint': '#00e479',
        'on-primary-fixed': '#00210c',
        'surface-container-highest': '#353534',
        'error': '#ffb4ab',
        'secondary-fixed-dim': '#00daf3',
        'on-secondary': '#00363d',
        'inverse-on-surface': '#313030',
        'primary-fixed': '#60ff99',
        'primary-fixed-dim': '#00e479',
        'surface-container': '#201f1f',
        'surface': '#131313',
        'tertiary-fixed': '#dae2fd',
        'surface-container-low': '#1c1b1b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Space Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'metric-xl': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.15em' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em' }],
        'metric-xl': ['48px', { lineHeight: '48px', letterSpacing: '-0.05em' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.04em' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
      },
    },
  },
  plugins: [],
}
